### PR TITLE
DVISA-1801: Parse Frame VOI LUT Sequence

### PR DESCRIPTION
**Pull request by muellnerlisa**
Adds parsing of the Frame VOI LUT Sequence which contains information about window width/center as well as information about the voi lut function type (for example SIGMOID).
The changes to the webpack files are included since they were not on our master branch (but we were using a tagged version containing these changes already)

### CODE REVIEW

**Comment by aminahasimbegovic** [comment]
Just a question for my understanding of this change - why wasn't this added to our WADO metadata provider?

**Comment by muellnerlisa** [comment]
> Just a question for my understanding of this change - why wasn't this added to our WADO metadata provider?

I needed to add it here because we need this information in our cornerstone fork and not in our project, in order to add the support for sigmoid (that's the PR for cornerstone where I am using the parsed data: https://github.com/DedalusDIIT/cornerstone/pull/4)

**Comment by aminahasimbegovic** [comment]
> > Just a question for my understanding of this change - why wasn't this added to our WADO metadata provider?
> 
> I needed to add it here because we need this information in our cornerstone fork and not in our project, in order to add the support for sigmoid (that's the PR for cornerstone where I am using the parsed data: [DedalusDIIT/cornerstone#4](https://github.com/DedalusDIIT/cornerstone/pull/4))

oh, I see, great, thanks for the explanation! :)

**Review by aminahasimbegovic — APPROVED** [review]

**Pull request merged**
